import { 
  FaPhone, 
  FaEnvelope, 
  FaMapMarkerAlt, 
  FaGlobe, 
  FaClock, 
  FaParking, 
  FaWifi, 
  FaCreditCard, 
  FaAccessibleIcon, 
  FaUtensils, 
  FaCocktail, 
  FaCoffee, 
  FaBed, 
  FaSwimmingPool, 
  FaConciergeBell, 
  FaFacebook, 
  FaTwitter, 
  FaInstagram, 
  FaLinkedin, 
  FaYoutube, 
  FaShoppingCart, 
  FaTshirt, 
  FaBook, 
  FaCar, 
  FaPlane, 
  FaTrain, 
  FaBus, 
  FaBicycle, 
  FaHospital, 
  FaGraduationCap, 
  FaDumbbell, 
  FaTheaterMasks, 
  FaMusic, 
  FaPaintBrush, 
  FaCamera, 
  FaGamepad, 
  FaPaw, 
  FaBabyCarriage, 
  FaToolbox, 
  FaCut, 
  FaSpa, 
  FaPizzaSlice, 
  FaBeer, 
  FaWineGlass, 
  FaIceCream, 
  FaCheck, 
  FaTree, 
  FaMountain, 
  FaUmbrellaBeach, 
  FaCampground, 
  FaHiking, 
  FaSkiing, 
  FaSnowboarding, 
  FaFish, 
  FaAnchor, 
  FaShip, 
  FaBinoculars, 
  FaShoppingBag, 
  FaPassport, 
  FaTicketAlt, 
  FaHotTub, 
  FaClinicMedical, 
  FaMosque, 
  FaChurch, 
  FaSynagogue, 
  FaLandmark, 
  FaMonument, 
  FaArchway, 
  FaGlasses, 
  FaFirstAid, 
  FaBolt, 
  FaFan, 
  FaHandsHelping, 
  FaLeaf, 
  FaRecycle, 
  FaSun, 
  FaStar, 
  FaGlobeAsia, 
  FaWarehouse, 
  FaHandshake, 
  FaChartBar 
} from 'react-icons/fa';

export const businessIcons = [
  { name: 'Phone', icon: FaPhone },
  { name: 'Email', icon: FaEnvelope },
  { name: 'Location', icon: FaMapMarkerAlt },
  { name: 'Website', icon: FaGlobe },
  { name: 'Hours', icon: FaClock },
  { name: 'Parking', icon: FaParking },
  { name: 'Wi-Fi', icon: FaWifi },
  { name: 'Credit Card', icon: FaCreditCard },
  { name: 'Accessibility', icon: FaAccessibleIcon },
  { name: 'Restaurant', icon: FaUtensils },
  { name: 'Bar', icon: FaCocktail },
  { name: 'Cafe', icon: FaCoffee },
  { name: 'Hotel', icon: FaBed },
  { name: 'Pool', icon: FaSwimmingPool },
  { name: 'Concierge', icon: FaConciergeBell },
  { name: 'Facebook', icon: FaFacebook },
  { name: 'Twitter', icon: FaTwitter },
  { name: 'Instagram', icon: FaInstagram },
  { name: 'LinkedIn', icon: FaLinkedin },
  { name: 'YouTube', icon: FaYoutube },
  { name: 'Shopping', icon: FaShoppingCart },
  { name: 'Clothing', icon: FaTshirt },
  { name: 'Book', icon: FaBook },
  { name: 'Car', icon: FaCar },
  { name: 'Plane', icon: FaPlane },
  { name: 'Train', icon: FaTrain },
  { name: 'Bus', icon: FaBus },
  { name: 'Bicycle', icon: FaBicycle },
  { name: 'Hospital', icon: FaHospital },
  { name: 'Education', icon: FaGraduationCap },
  { name: 'Gym', icon: FaDumbbell },
  { name: 'Theater', icon: FaTheaterMasks },
  { name: 'Music', icon: FaMusic },
  { name: 'Art', icon: FaPaintBrush },
  { name: 'Camera', icon: FaCamera },
  { name: 'Gaming', icon: FaGamepad },
  { name: 'Pet', icon: FaPaw },
  { name: 'Baby', icon: FaBabyCarriage },
  { name: 'Tools', icon: FaToolbox },
  { name: 'Salon', icon: FaCut },
  { name: 'Spa', icon: FaSpa },
  { name: 'Pizza', icon: FaPizzaSlice },
  { name: 'Beer', icon: FaBeer },
  { name: 'Wine', icon: FaWineGlass },
  { name: 'Ice Cream', icon: FaIceCream },
  { name: 'Check', icon: FaCheck },
  { name: 'Nature', icon: FaTree },
  { name: 'Mountain', icon: FaMountain },
  { name: 'Beach', icon: FaUmbrellaBeach },
  { name: 'Camping', icon: FaCampground },
  { name: 'Hiking', icon: FaHiking },
  { name: 'Skiing', icon: FaSkiing },
  { name: 'Snowboarding', icon: FaSnowboarding },
  { name: 'Fishing', icon: FaFish },
  { name: 'Anchor', icon: FaAnchor },
  { name: 'Ship', icon: FaShip },
  { name: 'Binoculars', icon: FaBinoculars },
  { name: 'Shopping Bag', icon: FaShoppingBag },
  { name: 'Passport', icon: FaPassport },
  { name: 'Ticket', icon: FaTicketAlt },
  { name: 'Hot Tub', icon: FaHotTub },
  { name: 'Clinic', icon: FaClinicMedical },
  { name: 'Mosque', icon: FaMosque },
  { name: 'Church', icon: FaChurch },
  { name: 'Synagogue', icon: FaSynagogue },
  { name: 'Landmark', icon: FaLandmark },
  { name: 'Monument', icon: FaMonument },
  { name: 'Archway', icon: FaArchway },
  { name: 'Glasses', icon: FaGlasses },
  { name: 'First Aid', icon: FaFirstAid },
  { name: 'Energy', icon: FaBolt },
  { name: 'Fan', icon: FaFan },
  { name: 'Helping Hands', icon: FaHandsHelping },
  { name: 'Eco-Friendly', icon: FaLeaf },
  { name: 'Recycle', icon: FaRecycle },
  { name: 'Sun', icon: FaSun },
  { name: 'Star', icon: FaStar },
  { name: 'Global', icon: FaGlobeAsia },
  { name: 'Storage', icon: FaWarehouse },
  { name: 'Handshake', icon: FaHandshake },
  { name: 'Statistics', icon: FaChartBar },
];
